<a href="https://colab.research.google.com/github/v1ctorvega/JSON_n_Pandas/blob/main/JSON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#JSON FILE READING WITH PANDAS

JSON files are lightweight text-based, human-readable files and can be edited using a text editor, **these files are useful to store simple data structures and objects in a specific format.**

The purpouse of this notebook is to practice JSON file manipulation with Pandas to reach a better comprehension of data through a simple in a  **Data Frame.**



![Imagen1.jpg]()

In [1]:
import requests
import json
import pandas as pd

In [2]:
url='https://raw.githubusercontent.com/bttmly/nba/master/data/teams.json'
req=requests.get(url)
print(req)

<Response [200]>

In [3]:
texto=req.text
texto

'[\n  {\n    "teamId": 1610612737,\n    "abbreviation": "ATL",\n    "teamName": "Atlanta Hawks",\n    "simpleName": "Hawks",\n    "location": "Atlanta"\n  },\n  {\n    "teamId": 1610612738,\n    "abbreviation": "BOS",\n    "teamName": "Boston Celtics",\n    "simpleName": "Celtics",\n    "location": "Boston"\n  },\n  {\n    "teamId": 1610612751,\n    "abbreviation": "BKN",\n    "teamName": "Brooklyn Nets",\n    "simpleName": "Nets",\n    "location": "Brooklyn"\n  },\n  {\n    "teamId": 1610612766,\n    "abbreviation": "CHA",\n    "teamName": "Charlotte Hornets",\n    "simpleName": "Hornets",\n    "location": "Charlotte"\n  },\n  {\n    "teamId": 1610612741,\n    "abbreviation": "CHI",\n    "teamName": "Chicago Bulls",\n    "simpleName": "Bulls",\n    "location": "Chicago"\n  },\n  {\n    "teamId": 1610612739,\n    "abbreviation": "CLE",\n    "teamName": "Cleveland Cavaliers",\n    "simpleName": "Cavaliers",\n    "location": "Cleveland"\n  },\n  {\n    "teamId": 1610612742,\n    "abbreviation": "DAL",\n    "teamName": "Dallas Mavericks",\n    "simpleName": "Mavericks",\n    "location": "Dallas"\n  },\n  {\n    "teamId": 1610612743,\n    "abbreviation": "DEN",\n    "teamName": "Denver Nuggets",\n    "simpleName": "Nuggets",\n    "location": "Denver"\n  },\n  {\n    "teamId": 1610612765,\n    "abbreviation": "DET",\n    "teamName": "Detroit Pistons",\n    "simpleName": "Pistons",\n    "location": "Detroit"\n  },\n  {\n    "teamId": 1610612744,\n    "abbreviation": "GSW",\n    "teamName": "Golden State Warriors",\n    "simpleName": "Warriors",\n    "location": "Golden State"\n  },\n  {\n    "teamId": 1610612745,\n    "abbreviation": "HOU",\n    "teamName": "Houston Rockets",\n    "simpleName": "Rockets",\n    "location": "Houston"\n  },\n  {\n    "teamId": 1610612754,\n    "abbreviation": "IND",\n    "teamName": "Indiana Pacers",\n    "simpleName": "Pacers",\n    "location": "Indiana"\n  },\n  {\n    "teamId": 1610612746,\n    "abbreviation": "LAC",\n    "teamName": "Los Angeles Clippers",\n    "simpleName": "Clippers",\n    "location": "Los Angeles"\n  },\n  {\n    "teamId": 1610612747,\n    "abbreviation": "LAL",\n    "teamName": "Los Angeles Lakers",\n    "simpleName": "Lakers",\n    "location": "Los Angeles"\n  },\n  {\n    "teamId": 1610612763,\n    "abbreviation": "MEM",\n    "teamName": "Memphis Grizzlies",\n    "simpleName": "Grizzlies",\n    "location": "Memphis"\n  },\n  {\n    "teamId": 1610612748,\n    "abbreviation": "MIA",\n    "teamName": "Miami Heat",\n    "simpleName": "Heat",\n    "location": "Miami"\n  },\n  {\n    "teamId": 1610612749,\n    "abbreviation": "MIL",\n    "teamName": "Milwaukee Bucks",\n    "simpleName": "Bucks",\n    "location": "Milwaukee"\n  },\n  {\n    "teamId": 1610612750,\n    "abbreviation": "MIN",\n    "teamName": "Minnesota Timberwolves",\n    "simpleName": "Timberwolves",\n    "location": "Minnesota"\n  },\n  {\n    "teamId": 1610612740,\n    "abbreviation": "NOP",\n    "teamName": "New Orleans Pelicans",\n    "simpleName": "Pelicans",\n    "location": "New Orleans"\n  },\n  {\n    "teamId": 1610612752,\n    "abbreviation": "NYK",\n    "teamName": "New York Knicks",\n    "simpleName": "Knicks",\n    "location": "New York"\n  },\n  {\n    "teamId": 1610612760,\n    "abbreviation": "OKC",\n    "teamName": "Oklahoma City Thunder",\n    "simpleName": "Thunder",\n    "location": "Oklahoma City"\n  },\n  {\n    "teamId": 1610612753,\n    "abbreviation": "ORL",\n    "teamName": "Orlando Magic",\n    "simpleName": "Magic",\n    "location": "Orlando"\n  },\n  {\n    "teamId": 1610612755,\n    "abbreviation": "PHI",\n    "teamName": "Philadelphia 76ers",\n    "simpleName": "76ers",\n    "location": "Philadelphia"\n  },\n  {\n    "teamId": 1610612756,\n    "abbreviation": "PHX",\n    "teamName": "Phoenix Suns",\n    "simpleName": "Suns",\n    "location": "Phoenix"\n  },\n  {\n    "teamId": 1610612757,\n    "abbreviation": "POR",\n    "teamName": "Portland Trail Blazers",\n    "simpleName": "Trail Blazers",\n    "location": "Portland"\n  },\n  {\n    "teamId": 1610612758,\n    "abbreviation": "SAC",\n    "teamName": "Sacramento Kings",\n    "simpleName": "Kings",\n    "location": "Sacramento"\n  },\n  {\n    "teamId": 1610612759,\n    "abbreviation": "SAS",\n    "teamName": "San Antonio Spurs",\n    "simpleName": "Spurs",\n    "location": "San Antonio"\n  },\n  {\n    "teamId": 1610612761,\n    "abbreviation": "TOR",\n    "teamName": "Toronto Raptors",\n    "simpleName": "Raptors",\n    "location": "Toronto"\n  },\n  {\n    "teamId": 1610612762,\n    "abbreviation": "UTA",\n    "teamName": "Utah Jazz",\n    "simpleName": "Jazz",\n    "location": "Utah"\n  },\n  {\n    "teamId": 1610612764,\n    "abbreviation": "WAS",\n    "teamName": "Washington Wizards",\n    "simpleName": "Wizards",\n    "location": "Washington"\n  }\n]'

In [4]:
jsondata=json.loads(texto)
jsondata

[{'teamId': 1610612737,
  'abbreviation': 'ATL',
  'teamName': 'Atlanta Hawks',
  'simpleName': 'Hawks',
  'location': 'Atlanta'},
 {'teamId': 1610612738,
  'abbreviation': 'BOS',
  'teamName': 'Boston Celtics',
  'simpleName': 'Celtics',
  'location': 'Boston'},
 {'teamId': 1610612751,
  'abbreviation': 'BKN',
  'teamName': 'Brooklyn Nets',
  'simpleName': 'Nets',
  'location': 'Brooklyn'},
 {'teamId': 1610612766,
  'abbreviation': 'CHA',
  'teamName': 'Charlotte Hornets',
  'simpleName': 'Hornets',
  'location': 'Charlotte'},
 {'teamId': 1610612741,
  'abbreviation': 'CHI',
  'teamName': 'Chicago Bulls',
  'simpleName': 'Bulls',
  'location': 'Chicago'},
 {'teamId': 1610612739,
  'abbreviation': 'CLE',
  'teamName': 'Cleveland Cavaliers',
  'simpleName': 'Cavaliers',
  'location': 'Cleveland'},
 {'teamId': 1610612742,
  'abbreviation': 'DAL',
  'teamName': 'Dallas Mavericks',
  'simpleName': 'Mavericks',
  'location': 'Dallas'},
 {'teamId': 1610612743,
  'abbreviation': 'DEN',
  'teamName': 'Denver Nuggets',
  'simpleName': 'Nuggets',
  'location': 'Denver'},
 {'teamId': 1610612765,
  'abbreviation': 'DET',
  'teamName': 'Detroit Pistons',
  'simpleName': 'Pistons',
  'location': 'Detroit'},
 {'teamId': 1610612744,
  'abbreviation': 'GSW',
  'teamName': 'Golden State Warriors',
  'simpleName': 'Warriors',
  'location': 'Golden State'},
 {'teamId': 1610612745,
  'abbreviation': 'HOU',
  'teamName': 'Houston Rockets',
  'simpleName': 'Rockets',
  'location': 'Houston'},
 {'teamId': 1610612754,
  'abbreviation': 'IND',
  'teamName': 'Indiana Pacers',
  'simpleName': 'Pacers',
  'location': 'Indiana'},
 {'teamId': 1610612746,
  'abbreviation': 'LAC',
  'teamName': 'Los Angeles Clippers',
  'simpleName': 'Clippers',
  'location': 'Los Angeles'},
 {'teamId': 1610612747,
  'abbreviation': 'LAL',
  'teamName': 'Los Angeles Lakers',
  'simpleName': 'Lakers',
  'location': 'Los Angeles'},
 {'teamId': 1610612763,
  'abbreviation': 'MEM',
  'teamName': 'Memphis Grizzlies',
  'simpleName': 'Grizzlies',
  'location': 'Memphis'},
 {'teamId': 1610612748,
  'abbreviation': 'MIA',
  'teamName': 'Miami Heat',
  'simpleName': 'Heat',
  'location': 'Miami'},
 {'teamId': 1610612749,
  'abbreviation': 'MIL',
  'teamName': 'Milwaukee Bucks',
  'simpleName': 'Bucks',
  'location': 'Milwaukee'},
 {'teamId': 1610612750,
  'abbreviation': 'MIN',
  'teamName': 'Minnesota Timberwolves',
  'simpleName': 'Timberwolves',
  'location': 'Minnesota'},
 {'teamId': 1610612740,
  'abbreviation': 'NOP',
  'teamName': 'New Orleans Pelicans',
  'simpleName': 'Pelicans',
  'location': 'New Orleans'},
 {'teamId': 1610612752,
  'abbreviation': 'NYK',
  'teamName': 'New York Knicks',
  'simpleName': 'Knicks',
  'location': 'New York'},
 {'teamId': 1610612760,
  'abbreviation': 'OKC',
  'teamName': 'Oklahoma City Thunder',
  'simpleName': 'Thunder',
  'location': 'Oklahoma City'},
 {'teamId': 1610612753,
  'abbreviation': 'ORL',
  'teamName': 'Orlando Magic',
  'simpleName': 'Magic',
  'location': 'Orlando'},
 {'teamId': 1610612755,
  'abbreviation': 'PHI',
  'teamName': 'Philadelphia 76ers',
  'simpleName': '76ers',
  'location': 'Philadelphia'},
 {'teamId': 1610612756,
  'abbreviation': 'PHX',
  'teamName': 'Phoenix Suns',
  'simpleName': 'Suns',
  'location': 'Phoenix'},
 {'teamId': 1610612757,
  'abbreviation': 'POR',
  'teamName': 'Portland Trail Blazers',
  'simpleName': 'Trail Blazers',
  'location': 'Portland'},
 {'teamId': 1610612758,
  'abbreviation': 'SAC',
  'teamName': 'Sacramento Kings',
  'simpleName': 'Kings',
  'location': 'Sacramento'},
 {'teamId': 1610612759,
  'abbreviation': 'SAS',
  'teamName': 'San Antonio Spurs',
  'simpleName': 'Spurs',
  'location': 'San Antonio'},
 {'teamId': 1610612761,
  'abbreviation': 'TOR',
  'teamName': 'Toronto Raptors',
  'simpleName': 'Raptors',
  'location': 'Toronto'},
 {'teamId': 1610612762,
  'abbreviation': 'UTA',
  'teamName': 'Utah Jazz',
  'simpleName': 'Jazz',
  'location': 'Utah'},
 {'teamId': 1610612764,
  'abbreviation': 'WAS',
  'teamName': 'Washington Wizards',
  'simpleName': 'Wizards',
  'location': 'Washington'}]

In [5]:
df=pd.DataFrame.from_dict(jsondata)
df

,teamId,abbreviation,teamName,simpleName,location
0,1610612737,ATL,Atlanta Hawks,Hawks,Atlanta
1,1610612738,BOS,Boston Celtics,Celtics,Boston
2,1610612751,BKN,Brooklyn Nets,Nets,Brooklyn
3,1610612766,CHA,Charlotte Hornets,Hornets,Charlotte
4,1610612741,CHI,Chicago Bulls,Bulls,Chicago
5,1610612739,CLE,Cleveland Cavaliers,Cavaliers,Cleveland
6,1610612742,DAL,Dallas Mavericks,Mavericks,Dallas
7,1610612743,DEN,Denver Nuggets,Nuggets,Denver
8,1610612765,DET,Detroit Pistons,Pistons,Detroit
9,1610612744,GSW,Golden State Warriors,Warriors,Golden State
10,1610612745,HOU,Houston Rockets,Rockets,Houston
11,1610612754,IND,Indiana Pacers,Pacers,Indiana
12,1610612746,LAC,Los Angeles Clippers,Clippers,Los Angeles
13,1610612747,LAL,Los Angeles Lakers,Lakers,Los Angeles
14,1610612763,MEM,Memphis Grizzlies,Grizzlies,Memphis
15,1610612748,MIA,Miami Heat,Heat,Miami
16,1610612749,MIL,Milwaukee Bucks,Bucks,Milwaukee
17,1610612750,MIN,Minnesota Timberwolves,Timberwolves,Minnesota
18,1610612740,NOP,New Orleans Pelicans,Pelicans,New Orleans
19,1610612752,NYK,New York Knicks,Knicks,New York
20,1610612760,OKC,Oklahoma City Thunder,Thunder,Oklahoma City
21,1610612753,ORL,Orlando Magic,Magic,Orlando
22,1610612755,PHI,Philadelphia 76ers,76ers,Philadelphia
23,1610612756,PHX,Phoenix Suns,Suns,Phoenix
24,1610612757,POR,Portland Trail Blazers,Trail Blazers,Portland
25,1610612758,SAC,Sacramento Kings,Kings,Sacramento
26,1610612759,SAS,San Antonio Spurs,Spurs,San Antonio
27,1610612761,TOR,Toronto Raptors,Raptors,Toronto
28,1610612762,UTA,Utah Jazz,Jazz,Utah
29,1610612764,WAS,Washington Wizards,Wizards,Washington

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   teamId        30 non-null     int64
 1   abbreviation  30 non-null     object
 2   teamName      30 non-null     object
 3   simpleName    30 non-null     object
 4   location      30 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.3+ KB

In [11]:
df.teamName.values #Lets visualize our Teams in our JSON file through a single array

array(['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets',
       'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Dallas Mavericks', 'Denver Nuggets', 'Detroit Pistons',
       'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies',
       'Miami Heat', 'Milwaukee Bucks', 'Minnesota Timberwolves',
       'New Orleans Pelicans', 'New York Knicks', 'Oklahoma City Thunder',
       'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns',
       'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs',
       'Toronto Raptors', 'Utah Jazz', 'Washington Wizards'], dtype=object)